### ISSUE TITLE
No method to verify essential claims

### ISSUE THREAD

**Issue by gcallaghan** [lestrrat/go-jwx#10]
Many top level JWT libraries have checks that verify the following claims. 
- iss 
- sub 
- aud 
- exp
- nbf 
- iat
- jti 

I was surprised when calling jws.Verify on an expired token did not return an error. The jwt package could probably benefit from a high level Verify function that verified the signature as well as the essential claims.

**Comment by lestrrat** [comment]
true that. I'm a bit swamped atm, would you be willing to provide me with a failing test case?

**Comment by gcallaghan** [comment]
I'll try to provide a patch in the next couple of days.

**Comment by samtech09** [comment]
I got same issue, not verifying Essential claims. I set follwoing 
IssuedAt = 1 Hr ago from now
Expiration = 2 min from IssuedAt
NotBefore = Future date (3 days next)

Still it is not complaining and verifying the token. Here is the code

`package main

import(
  "encoding/json"
  "log"
  "crypto/rand"
  "crypto/rsa"
  "time"

  "github.com/lestrrat/go-jwx/jwt"
  "github.com/lestrrat/go-jwx/jwa"
  "github.com/lestrrat/go-jwx/jws"
)

func main() {
  c := jwt.NewClaimSet()
  c.Set("sub", "jwt-essential-claim-verification")
  
  // issuedat = 1 Hr before current time
  c.IssuedAt = time.Now().Unix() - 3600  
  
  // valid for 2 minutes only from IssuedAt
  c.Expiration = c.IssuedAt + 120  

  // NotBefore is set to future date
  t := time.Now().Add(time.Duration(72)*time.Hour)
  c.NotBefore = &jwt.NumericDate{t}

  //get json 
  buf, err := json.MarshalIndent(c, "", "  ")
  if err != nil {
    log.Printf("failed to generate JSON: %s", err)
    return
  }

  // generte rsa key
  rsakey, err := rsa.GenerateKey(rand.Reader, 2048)
  if err != nil {
    log.Printf("failed to generate private key: %s", err)
    return
  }

  // sign payload
  sbuf, err := jws.Sign(buf, jwa.RS256, rsakey)
  if err != nil {
    log.Printf("failed to created JWS message: %s", err)
    return
  }


  //Verify signature and grab payload
  verified, err := jws.Verify(sbuf, jwa.RS256, &rsakey.PublicKey)
  if err != nil {
    log.Printf("failed to verify message: %s", err)
    return
  }

  log.Println("==================================")
  log.Println("JWS verified even expired!!!")

  //get claimset
  cs := jwt.NewClaimSet()
  err = cs.UnmarshalJSON(verified)
  if err != nil {
    log.Printf("failed to get claimset: %s", err)
    return
  }
  // print Essential claims
  log.Printf("IssuedAt: %v", time.Unix(cs.IssuedAt, 0))
  log.Printf("Expiration: %v", time.Unix(cs.Expiration, 0))
  log.Printf("NotBefore: %v", cs.NotBefore)
}
`

**Comment by lestrrat** [comment]
Okay, looking at the code, I think `jws.Verify()` is definitely not the right place to do this check. we probably should just have a `jwt.Verify()` that does this.

**Comment by samtech09** [comment]
yes that is missing.
jws should verify the Signaure and
jwt should verify essential claims

**Comment by lestrrat** [comment]
@samtech09 still just tinkering, and many more stuff missing, but how about an API like this

https://github.com/lestrrat/go-jwx/commit/79ceea82d88c894bd365300281a906ed2f9219d1

**Comment by samtech09** [comment]
It looks good and easy to use that's why i am exploring it :+1: 
But without those basic checks it is not usable.

**Comment by samtech09** [comment]
yes that API [ verifyEssentialClaims() and jwt.Verify ] will solve the purpose.

**Comment by lestrrat** [comment]
Please check #20, and see if this works.

**Comment by samtech09** [comment]
Great, it is working as expected !!

After signature verification, i need to call 
err = cs.Verify()
