### ISSUE TITLE
Can u publish this on https://jwt.io/ ?

### ISSUE THREAD

**Issue by sillysachin** [lestrrat/go-jwx#19]
Can u publish this on https://jwt.io/

Examples on https://jwt.io/
1. github.com/dvsekhvalnov/jose2go
2. github.com/dgrijalva/jwt-go
3. github.com/SermoDigital/jose
4. github.com/robbert229/jwt

Also are there any tutorials using this in client facing examples?

**Comment by lestrrat** [comment]
I'm not affiliated with jwt.io, so it's not up to me to decide if it should be on that site.

**Comment by hopkinsth** [comment]
Looked into this a little more, and jwt.io has a repo where you can submit a pull request for inclusion: https://github.com/jsonwebtoken/jsonwebtoken.github.io

Didn't spend much time looking at their jade templates to understand the exact changes you'd need to make to submit a PR, but... if you're cool with this being added to jwt.io @lestrrat, I can submit it sometime. This is proving to be the only Go JWS/JWT library that _actually_ does what I need it to do without a huge hassle. (Thanks!)

**Comment by lestrrat** [comment]
@hopkinsth cool! I'm looking at it myself right now, but if in the future you notice that I haven't done it, pls just go ahead and file it for me :)

**Comment by lestrrat** [comment]
Hmm, I now know how to modify their site, but I wonder what they really mean when they say "iss" et al is checked...

**Comment by lestrrat** [comment]
https://github.com/jsonwebtoken/jsonwebtoken.github.io/pull/259

**Comment by lestrrat** [comment]
...and after three months, it has been merged.
