### ISSUE TITLE
Consider not rounding time or set `skew` to 1 in token validation

### ISSUE THREAD

**Issue by wvh** [lestrrat/go-jwx#37]
Hello,

When doing JWT claim validation, `iat` and `Now()` are rounded to the nearest second before the comparison with `now.After()` (see  `jwt/verify.go:174`). This means that by default, tokens are always invalid in the same second they are created. It's probably very common for a server to respond with a token to a client which then immediately tries to validate it, which will very likely result in a validation error because of `iat`.

Setting `skew` works, but maybe the default skew could be 1 second or the comparison could be done without rounding the times, so by default, tokens are not invalid in the same second they are created.

Go has a `time.After()` and `time.Equal`, but no `time.AfterOrEqual`. Another option could also be to reverse the condition and use `time.Before()`.

**Comment by lestrrat** [comment]
Can you please provide a failing test case?

**Comment by lestrrat** [comment]
@wvh thanks for the test!

I amended your tests to avoid races, and allowed iat == now (truncated up to seconds) on #41
Let me know if it works for you?

**Comment by wvh** [comment]
The check `now != ttv` fails.

`clock.Now().Truncate(time.Second)` is in local time, and `tv.Time.Truncate(time.Second)` is in UTC:

```go
fmt.Printf("%d == %d: %t\n", now, ttv, now == ttv)
{0 63654631131 9201856} == {0 63654631131 0}: false
```
If you compare the structs directly, the timezone might be different. It can be fixed by adding a `.UTC()`  call to`clock.Now().UTC().Truncate(time.Second)`, using `time.Equal()` instead, or reversing the condition to use `.Before()` instead of `.Equal` and `.After`.

It might be better not to depend on struct comparison as the Go developers might change the fields internally like they did with the monotonic time improvements.

**Comment by lestrrat** [comment]
Yeah, that's a total screw up on my part. I totally meant to use Equal/After, but I don't know what I was thinking. nice catch :)
