### ISSUE TITLE
Loading JSON Web Keys from a String or []byte, can't figure it out.

### ISSUE THREAD

**Issue by pmcdowell-okta** [lestrrat/go-jwx#42]
This isn't a bug, but damn if I cannot figure out how to load keys from a Array or String, not a URL

`set, err := jwk.Fetch(keyUrl) //This works
`
I'm trying to figure out how to load them directly, or create them from the keys I already have.

I kicked around doing something like this:

`set,err:=jwk.New(array_like_json_string_below) //This is what I want to do
`
I'm trying to persist them, and not load them everytime.

The keys are the JSON format.
```
{"keys":
[{"alg":"RS256","e":"AQAB","n":"jqm5oX5Vth4JW1gZQHywIki2beYCgBSL-
EYlefDUlI6SShtEKfi-vWYbFh2pNNUAE4NHuYpYP-
FG1uRSKs6WK2k6KMB2Hyx3hBkWyu7Aqo_pb1WItkPSZS-AWOMp4N-
```
Thanks for help, great library

**Comment by lestrrat** [comment]
I'm not around my PC so this is just a quick repsponse, but you shouldbe able to use json.Unmarshal

**Comment by pmcdowell-okta** [comment]
Thanks for getting back, no rush.

I hope I was making sense, I basically want to do something like this.

`set,err:=jwk.New("{"keys":[{"alg":"RS256","e"... //Psuedo code.
`
Thanks again for the library

**Comment by lestrrat** [comment]
yeah but what exactly json.Unmarshal is for

**Comment by lestrrat** [comment]
@pmcdowell-okta well, duh. OK, so I hadn't re-read my code in a while so I forgot, but there's a Parse func. https://godoc.org/github.com/lestrrat/go-jwx/jwk#Parse. I guess it's a documentation issue, but I'd appreciate a PR for it.
